In [20]:
import pandas as pd
from numpy import nan
from numpy import isnan
from sklearn.impute import SimpleImputer
df = pd.read_csv('potato.csv')

Empty DataFrame
Columns: [Date, p/kg, Arrival]
Index: []

In [12]:
values=df[['p/kg','Arrival']]

In [7]:
imputer=SimpleImputer(missing_values=nan,strategy='mean')

In [18]:
transformed_values=imputer.fit_transform(values)
print(transformed_values)

[[  63.          600.        ]
 [  66.          350.        ]
 [  68.          450.        ]
 [  70.          600.        ]
 [  70.         1395.55555556]
 [  66.          400.        ]
 [  62.          400.        ]
 [  62.          300.        ]
 [  60.          250.        ]
 [  60.          200.        ]
 [  63.         1395.55555556]
 [  63.         1395.55555556]
 [  62.          350.        ]
 [  69.          450.        ]
 [  68.          250.        ]
 [  63.          550.        ]
 [  58.          400.        ]
 [  60.          200.        ]
 [  60.         1395.55555556]
 [  60.          750.        ]
 [  60.          250.        ]
 [  60.          200.        ]
 [  60.          450.        ]
 [  60.          300.        ]
 [  60.          250.        ]
 [  60.         1395.55555556]
 [  62.          150.        ]
 [  66.         1395.55555556]
 [  66.          300.        ]
 [  62.          200.        ]
 [  62.          350.        ]
 [  60.          300.        ]
 [  60.         1395.55555556]
 [  60.          300.        ]
 [  62.          250.        ]
 [  66.          200.        ]
 [  66.          200.        ]
 [  66.          350.        ]
 [  60.          150.        ]
 [  60.         1395.55555556]
 [  62.          300.        ]
 [  60.          300.        ]
 [  64.          300.        ]
 [  62.          300.        ]
 [  66.          250.        ]
 [  64.          350.        ]
 [  64.         1395.55555556]
 [  61.          200.        ]
 [  61.         1395.55555556]
 [  64.          450.        ]
 [  64.          450.        ]
 [  62.          300.        ]
 [  62.          350.        ]
 [  67.         1395.55555556]
 [  67.          500.        ]
 [  68.          350.        ]
 [  71.          350.        ]
 [  73.          400.        ]
 [  72.          100.        ]
 [  73.          400.        ]
 [  73.         1395.55555556]
 [  71.          250.        ]
 [  71.          250.        ]
 [  70.          650.        ]
 [  73.          550.        ]
 [  76.          500.        ]
 [  76.          750.        ]
 [  76.         1395.55555556]
 [  78.          500.        ]
 [  77.          450.        ]
 [  80.          800.        ]
 [  76.          450.        ]
 [  76.          550.        ]
 [  68.          850.        ]
 [  68.         1395.55555556]
 [  72.          400.        ]
 [  73.          400.        ]
 [  73.          300.        ]
 [  70.          800.        ]
 [  70.          600.        ]
 [  69.          550.        ]
 [  69.         1395.55555556]
 [  70.         1700.        ]
 [  67.         2400.        ]
 [  68.         1200.        ]
 [  66.         2500.        ]
 [  66.         1600.        ]
 [  67.         2300.        ]
 [  67.         1395.55555556]
 [  68.         2500.        ]
 [  69.         2200.        ]
 [  67.         5200.        ]
 [  63.         5150.        ]
 [  59.         6800.        ]
 [  56.         7600.        ]
 [  56.         9900.        ]
 [  55.         1395.55555556]
 [  55.         4400.        ]
 [  54.         5300.        ]
 [  48.         5300.        ]
 [  44.         5600.        ]
 [  40.         3300.        ]
 [  36.         4600.        ]
 [  36.         1395.55555556]
 [  36.         3800.        ]
 [  36.         6600.        ]
 [  34.         4500.        ]
 [  34.         5200.        ]]

In [16]:
print('Missing: %d' % isnan(transformed_values).sum())

Missing: 0

In [17]:
df.head(10)

     Date  p/kg  Arrival
0  01-Sep    63    600.0
1  02-Sep    66    350.0
2  03-Sep    68    450.0
3  04-Sep    70    600.0
4  05-Sep    70      NaN
5  06-Sep    66    400.0
6  07-Sep    62    400.0
7  08-Sep    62    300.0
8  09-Sep    60    250.0
9  10-Sep    60    200.0

Empty DataFrame
Columns: [Date, p/kg, Arrival]
Index: []

In [ ]:
num_test = X_test.shape[0]
    Y_pred = np.zeros(num_test, dtype=int)
    dists = euclidean_dist(X_test, X_train)
    
    neighbors = find_k_neighbors(dists, Y_train, k)
    for i in range(num_test):
        
        value, counts = np.unique(neighbors[i], return_counts=True)
        idx = np.argmax(counts)
        Y_pred[i] = value[idx]
        
        if X_test.shape[0]>0:
            
            new_dist=euclidean_dist(pd.Series(X_test[0]),X_train)
           
            np.append(dicts,new_dist[0])
            
            Y_train=Y_train.append(pd.Series([Y_pred[i]],index=[X_train.shape[0]]))
            # print(Y_train.tail(5))
            neighbors = find_k_neighbors(dists, Y_train, k)
            X_train=X_train.append(pd.Series([X_test[0]],index=[X_train.shape[0]]))
            X_test=X_test[1:]